### PR TITLE
addressing recent issues

### LINKED ISSUE #79: A reference that can be added
Came across this today

Sansone S-A, McQuilton P, Rocca-Serra P, Gonzalez-Beltran A, Izzo M, Lister AL, Thurston M (2019) FAIRsharing as a community approach to standards, repositories and policies. Nat Biotechnol 37(4):358–367

### LINKED ISSUE #81: FAQ link for NIH page
from @vortexing on slack:

The [link](https://osp.od.nih.gov/scientific-sharing/nih-policy-for-data-management-and-sharing-faq/) to the DMS policy FAQ link listed here https://hutchdatascience.org/NIH_Data_Sharing/faq.html is broken.
Perhaps it should be https://sharing.nih.gov/faqs#/data-management-and-sharing-policy.htm?

### LINKED ISSUE #82: New DMS examples from the NIH
Sandy shared that there are new example DMS plans from teh NIH that we should refer to in the guide:

https://sharing.nih.gov/data-management-and-sharing-policy/planning-and-budgeting-for-data-management-and-sharing/writing-a-data-management-and-sharing-plan#sample-plans

I'll also put them on the NIH page on our site too.

### LINKED ISSUE #83: add guidance on no hyperlinks
https://nexus.od.nih.gov/all/2023/01/10/dms-plan-tip-leave-the-hypertext-at-home/

Add no hyperlinks to main messages

### PR DESCRIPTION
**Pull request by carriewright11**
resolves #83  and resolves #81  and resolves #79 and resolves #82 

- saying no hyperlinks in overall takeaways
- saying no hyperlinks in writing section

Anywhere else we need to? Is it emphatic enough? This thing Jeff sent is kinda intense: https://nexus.od.nih.gov/all/2023/01/10/dms-plan-tip-leave-the-hypertext-at-home/

### CODE REVIEW

**Comment by carriewright11** [comment]
@avahoffman  does this link seem kinda equivalent to the activity code link that is broken that we had before: https://sharing.nih.gov/node/112

I can't quite recall what it was like

**Comment by avahoffman** [comment]
> @avahoffman does this link seem kinda equivalent to the activity code link that is broken that we had before: https://sharing.nih.gov/node/112
> 
> I added it, but there is also this option: https://sharing.nih.gov/data-management-and-sharing-policy/about-data-management-and-sharing-policies/research-covered-under-the-data-management-sharing-policy#research-covered-by-the-2023-data-management-&-sharing-policy
> 
> I can't quite recall what it was like

Yes I think that's basically what it was!

**Review by avahoffman — APPROVED** [review]
LGTM! 

Also edited this slide :)

image

**Comment by carriewright11** [comment]
> LGTM!
> 
> Also edited this slide :)
> 


Perfect - thanks!

**Pull request merged**
