### PR TITLE
Fix Reference weirdness - resolves #45

### LINKED ISSUE #45: References in chapter 5 are rendering weird
image

### PR DESCRIPTION
**Pull request by avahoffman**
Attempting to address #45  - Reference rendering weirdness.

### CODE REVIEW

**Comment by avahoffman** [comment]
@carriewright11 @vortexing @ehumph I just moved this bit. It was the placement right before a new "PART" in the organization that was causing this.

**Comment by carriewright11** [comment]
should we maybe move this to the appendix?

**Comment by avahoffman** [comment]
@carriewright11 how do you feel about this?

- A "Further Reading" chapter in the appendix
- References only at the end (not by chapter)

**Comment by carriewright11** [comment]
> @carriewright11 how do you feel about this?
> 
> * A "Further Reading" chapter in the appendix
> * References only at the end (not by chapter)

Yeah, that seems good!

**Comment by carriewright11** [comment]
Might want a space here:
Screen Shot 2022-11-04 at 10 23 08 AM

**Comment by carriewright11** [comment]
Now that you removed the references from each chapter though, I think it would be OK earlier in the writing chapter if you prefer having it there. Whatever you like best works for me.

**Comment by avahoffman** [comment]
> Now that you removed the references from each chapter though, I think it would be OK earlier in the writing chapter if you prefer having it there. Whatever you like best works for me.

Yes! Meant to add that space and got distracted :P

**Comment by carriewright11** [comment]
> > Now that you removed the references from each chapter though, I think it would be OK earlier in the writing chapter if you prefer having it there. Whatever you like best works for me.
> 
> Yes! Meant to add that space and got distracted :P

There's only a thousand details just in one of our courses :P

**Comment by avahoffman** [comment]
@carriewright11 look ok now?

**Review by carriewright11 — APPROVED** [review]

**Pull request merged**
