### PR TITLE
Add authors - resolves #51

### LINKED ISSUE #51: authors
we will want to update this section too

### PR DESCRIPTION
**Pull request by ehumph**
Adds the authors and contributors, thus resolving issue #51

### CODE REVIEW

**Comment by carriewright11** [comment]
sounds like we might need to add Sean if we include the cheat sheet - I think he helped format that... maybe that goes in illustration or graphics?

**Comment by ehumph** [comment]
Oops, I'll add Sean - I didn't realize he'd been involved. It is hard to keep track of what everyone has done. (:

**Comment by carriewright11** [comment]
> Oops, I'll add Sean - I didn't realize he'd been involved. It is hard to keep track of what everyone has done. (:

Oh don't feel bad at all - I just noticed on Basecamp (I think) that Amy mentioned that he helped format the cheat sheet yesterday

**Comment by carriewright11** [comment]
I think this is a great start. We might want to see what else happens with the templates and other resources too.

**Review by avahoffman — APPROVED** [review]
lgtm , we can always update later!

**Pull request merged**
