### PR TITLE
Do some theming cleanup

### PR DESCRIPTION
**Pull request by avahoffman**
Conform to changes made by @vortexing for consistent logo/theming

For reference:  
- https://github.com/jhudsl/OTTR_Template/pull/598
- https://github.com/fhdsl/FH_WDL101_Cromwell/pull/8
- https://github.com/fhdsl/FH_WDL101_Cromwell/pull/5
- https://github.com/fhdsl/FH_Cluster_Guide/pull/65

### CODE REVIEW

**Comment by carriewright11** [comment]
I added a button for feedback and the mountains to the footer. Do we want the top logo of the TOC to be centered or left-aligned like it is now? (I could adjust it if you like)

**Comment by carriewright11** [comment]
I had actually already added padding to the feedback button

**Comment by carriewright11** [comment]
> Looks great! I added some margin to the feedback box
> 
> image

yeah I had done that too

**Comment by carriewright11** [comment]
hmm now the span doesn't fit

**Comment by carriewright11** [comment]
do you mind if I try undoing one of our adjustments

**Comment by avahoffman** [comment]
> I had actually already added padding to the feedback button



> > Looks great! I added some margin to the feedback box
> > image
> 
> yeah I had done that too

It was `padding` not `margin` - I didn't see the space before

**Comment by carriewright11** [comment]
> > I had actually already added padding to the feedback button
> 
> > > Looks great! I added some margin to the feedback box
> > > image
> > 
> > 
> > yeah I had done that too
> 
> It was `padding` not `margin` - I didn't see the space before

what I mean is ... I did it with the trapezoid css

**Comment by avahoffman** [comment]
Is this not what we want?
image

**Comment by carriewright11** [comment]
> Is this not what we want? image

see how the cursor doesnt fit now?

**Comment by avahoffman** [comment]
> > Is this not what we want? image
> 
> see how the cursor doesnt fit now?

Oh gotcha, I kinda like that! :)

**Comment by carriewright11** [comment]
Screen Shot 2022-11-02 at 1 14 07 PM
This is what mine looks like

**Comment by avahoffman** [comment]
Alright, reverted my change. sorry about that!

**Comment by carriewright11** [comment]
> > > Is this not what we want? image
> > 
> > 
> > see how the cursor doesnt fit now?
> 
> Oh gotcha, I kinda like that! :)

I mean if you like it we can go for that

**Comment by carriewright11** [comment]
> Alright, reverted my change. sorry about that!

no problem! we were just doing the same things at the same time (only differently :P)

**Comment by carriewright11** [comment]
do you like how the top logo is now too? I moved it to be more centered

**Comment by avahoffman** [comment]
yes looks great!

**Comment by carriewright11** [comment]
and also the footer?
Screen Shot 2022-11-02 at 1 18 13 PM

**Comment by carriewright11** [comment]
maybe we can leave this PR up for people to see if they like the new changes?

**Comment by avahoffman** [comment]
@ehumph @vortexing @cansavvy please provide feedback on the theme/icons/buttons etc here ([preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/fhdsl/NIH_Data_Sharing/preview-33/docs/index.html)). It's important we stay consistent with the theming/style across courses. Gotta have that nice branding 🙂

**Comment by cansavvy** [comment]
> @ehumph @vortexing @cansavvy please provide feedback on the theme/icons/buttons etc here ([preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/fhdsl/NIH_Data_Sharing/preview-33/docs/index.html)). It's important we stay consistent with the theming/style across courses. Gotta have that nice branding 🙂

This looks good to me! But I don't generally have a ton of opinions about aesthetics.

**Comment by avahoffman** [comment]
> > @ehumph @vortexing @cansavvy please provide feedback on the theme/icons/buttons etc here ([preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/fhdsl/NIH_Data_Sharing/preview-33/docs/index.html)). It's important we stay consistent with the theming/style across courses. Gotta have that nice branding 🙂
> 
> This looks good to me! But I don't generally have a ton of opinions about aesthetics.

If nothing else, just want to make sure you see it :)

**Comment by ehumph** [comment]
@avahoffman I like it!

**Comment by carriewright11** [comment]
Should resolve issue #4

**Comment by vortexing** [comment]
Full Support!!!!   My only last thought on theme stuff is the font - I'm fuzzy on where the fonts are chosen for the various products that get made.  I believe C&M suggested Arial for the text and Times for the headers? 

> "The Fred Hutch visual system uses Tiempos Headline for the display type and Circular for the informational type. They work side-by-side to convey information in a harmonious manner."

So for us that would be Times for "display"?? and Arial for "informational"?  I'm not sure how to translate that into our stuff and also in a sane way.

**Comment by avahoffman** [comment]
@vortexing do you think we'll get scolded if we keep the header and text fonts of the course itself as is?

Here's where we can look at a preview: https://github.com/fhdsl/NIH_Data_Sharing/pull/43 ... not yet rendered as Actions is degrated ATM https://www.githubstatus.com/ 🙃

**Comment by carriewright11** [comment]
> @vortexing do you think we'll get scolded if we keep the header and text fonts of the course itself as is?
> 
> Here's where we can look at a preview with arial and TNR adjacent fonts: #43 ... not yet rendered as Actions is degrated ATM https://www.githubstatus.com/ 🙃
> 
> edit:
> 
> Nevermind! saw @carriewright11 's [dc42dc4](https://github.com/fhdsl/NIH_Data_Sharing/commit/dc42dc493a68aa0c27f6afd51ec8fdbf872b2a8e)

oh sorry I was just checking it. I can add those changes here if you want but Ava's yours works too

**Comment by avahoffman** [comment]
> oh sorry I was just checking it. I can add those changes here if you want but Ava's yours works too - I was doing actual arial and TNR - looks OK

Happy to do Arial and TNR (wasn't sure that would work) - Feel free to revert your revert @carriewright11  :)

**Comment by carriewright11** [comment]
Ava is opening a new font PR so I will merge this one now

**Pull request merged**
