### PR TITLE
Delete spell_check_results.tsv from the gitignore

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?

Related to: https://github.com/jhudsl/OTTR_Template/issues/580#issuecomment-1287250410

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks good to me! not sure what the url checker issue is about - this was fine with no updates to the urls in the previous PR

**Comment by avahoffman** [comment]
Yeah, the urls have been an issue in all of my other repos in the last day or so.

**Comment by cansavvy** [comment]
It’s a separate problem: https://github.com/jhudsl/OTTR_Template/issues/590 that I’m actively trying to fix but it isn’t related to this repo so you can ignore it for now. Hope to have a fix for it by the end of today

**Review by avahoffman — APPROVED** [review]

**Comment by carriewright11** [comment]
It seems to dislike having a link inside at the end of a  statement in parentheses

**Review by carriewright11 — COMMENTED** [review]
Thanks!

**Comment by cansavvy** [comment]
> Yeah, the urls have been an issue in all of my other repos in the last day or so.

Trying to get that fixed today. Ignore for now.

**Comment by avahoffman** [comment]
@cansavvy no rush / worries! Just making it clear that it's not this repo.

**Comment by carriewright11** [comment]
> @cansavvy no rush / worries! Just making it clear that it's not this repo.

agreed! no rush!

**Pull request merged**
