### PR TITLE
Add page about DMS Helper App

### PR DESCRIPTION
**Pull request by avahoffman**
- Adding a page so that folks can easily find the app at https://dmshelper.fredhutch.org/
- Adding a callout box to the app in the writing section
- Also noticed the repo name was incorrect in `_bookdown.yml`

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks great! I kinda wonder if this should go at the beginning of the writing the plan section (just seems like the most relevant spot)? I could be persuaded to keep it where it is though!

I also noticed that we use a different acronym for the plan between the app and the course - should we choose one to stay consistent?

Thanks for fixing the repo link!

**Comment by avahoffman** [comment]
> Looks great! I kinda wonder if this should go at the beginning of the writing the plan section (just seems like the most relevant spot)? I could be persuaded to keep it where it is though!

I was hoping to make sure folks saw it early, and were aware of its existence. I don't want it to get buried.

> I also noticed that we use a different acronym for the plan between the app and the course - should we choose one to stay consistent? DMSP vs DSMP

I think this might be a *tad* confusing, but I thought DSM Plan Helper would be too long of a url / title. 

> Thanks for fixing the repo link!

NP!

> I also noticed we have some warning messages in the about this course section after the first paragraph

Addressed in https://github.com/fhdsl/NIH_Data_Sharing/pull/96

**Comment by carriewright11** [comment]
oops sorry didn't mean to edit your comment! Idk how I did that!!

**Comment by avahoffman** [comment]
@carriewright11 no worries. I have to change the library name and shiny deployment so that might take a bit.

And yes, I think a shoutout at the writing stage is a good idea. will add!

**Comment by avahoffman** [comment]
@carriewright11 that didn't take as long as I thought 😜 How are things looking now?

**Comment by carriewright11** [comment]
> @carriewright11 that didn't take as long as I thought 😜 How are things looking now?

I will look!

**Comment by avahoffman** [comment]
- [ ] @avahoffman Restore branch to main on `cow::borrow_chapter` once approved

**Comment by carriewright11** [comment]
Looks great!

**Review by carriewright11 — APPROVED** [review]

**Pull request merged**
