### PR TITLE
Adding TLDR info

### LINKED ISSUE #66: add a TLDR summary to beginning
Jeff said he didn't see the review process section - so  he suggested adding this

### PR DESCRIPTION
**Pull request by carriewright11**
Resolves #66 
also want to hold off on including Beth's email for a bit (discussed in the meeting today)

### CODE REVIEW

**Comment by carriewright11** [comment]
How about something like this:

Screen Shot 2022-11-10 at 2 25 03 PM

We could add the slide image at the end of the course maybe?

**Comment by avahoffman** [comment]
I think the contents are great. As mentioned in #66 I think we should probably break it up into smaller bits if they are going to be text-on-slide, if no other reason than the text is small :)

**Comment by carriewright11** [comment]
> I think the contents are great. As mentioned in #66 I think we should probably break it up into smaller bits if they are going to be text-on-slide, if no other reason than the text is small :)

OK - Are we good then with the style of this text-within-the-text version? Maybe if we decide to do slides it could be at the end or somewhere else? I wasn't sure if by "contents are great" you meant the wording or this option of putting the takeaways in the text with the styling I did. I know you wanted people to be able to copy the text too, so I was thinking we at least give that option this way. I will keep thinking about how we could do slide versions.

**Review by ehumph — APPROVED** [review]
I like this version of the graphic!

**Comment by avahoffman** [comment]
@carriewright11 I'm sorry! I thought this was another google slide. I love it!

**Review by avahoffman — APPROVED** [review]
@carriewright11 Crushed this!! 🙌🏻

**Comment by carriewright11** [comment]
> @carriewright11 I'm sorry! I thought this was another google slide. I love it!

No worries :) I'm glad you like it!

**Pull request merged**
