### PR TITLE
More repos

### PR DESCRIPTION
**Pull request by carriewright11**
Realized in searching for metabolomics repositories that sometimes the links people need are not in the interactive table and so I want to emphasize that they should look in the other links that NIH provided too.

I also added a bit more about data management - linking people to the appendix and the computing course in case people need that. I used the image about phones as motivation for that so I moved that up from the repository section.

I also added a summary at the end with all the links

### CODE REVIEW

**Comment by carriewright11** [comment]
Screen Shot 2022-11-07 at 11 11 42 AM
I am trying to modify @avahoffman's beautiful flowchart to also emphasize these resources, needs some help but I think I might be getting somewhere.

**Review by avahoffman — APPROVED** [review]
LGTM! Only thing I might add is a screenshot of the table

**Review by ehumph — APPROVED** [review]
LGTM!

**Comment by carriewright11** [comment]
> LGTM! Only thing I might add is a screenshot of the table

ooh I like that idea!

**Comment by carriewright11** [comment]
> > LGTM! Only thing I might add is a screenshot of the table
> 
> ooh I like that idea!

oh wait I am confused... we already have the interactive table - do you mean some of the others?

**Comment by carriewright11** [comment]
> > > LGTM! Only thing I might add is a screenshot of the table
> > 
> > 
> > ooh I like that idea!
> 
> oh wait I am confused... we already have the interactive table - do you mean some of the others?

I do think we should move that though...

**Comment by avahoffman** [comment]
> I do think we should move that though...

Nope, I'm just confused and missed it in the preview for some reason! feel free to move it around.

**Comment by carriewright11** [comment]
> > I do think we should move that though...
> 
> Nope, I'm just confused and missed it in the preview for some reason! feel free to move it around.

I forgot about it too!

**Pull request merged**
